spring:
  profiles:
    default: local #??????? Spring ?? ?????????
  datasource: #????????? ?????????? ? ???? ?? ?????????
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres #????? ????????????? ????? ?????????? ?????????
    username: postgres
    password: SRr729038
  jpa:
    show-sql: true #?? ????????? ???????? ????? SQL
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update

---
spring:
  config.activate.on-profile: test #?????????? ???????? ???????? ??? ????????? ??????? 
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect #?????????? H2 ??? ??????
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres #????? ????????????? ????? ?????????? ?????????
    username: postgres
    password: SRr729038
  liquibase:
    user: postgres
    password: SRr729038
    contexts: schema