spring:
  profiles:
    default: local #профиль Spring по умолчанию
  datasource: #настройки соединения с СУБД по умолчанию
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL} #будут опеределяться через переменную окружения
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: false #по умолчанию отключим показ SQL
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  liquibase:
    enabled: true #включён по умолчанию
    contexts: schema, data #контексты по умолчанию
    change-log: classpath:db.changelog.xml #путь к журналу изменений Liquibase
    liquibaseSchema: liquibase #служебная схема СУБД для liquibase
    default-schema: dict #схема СУБД для приложения
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
---
spring:
  config.activate.on-profile: test #расширение основных настроек для тестового профиля
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect #используем H2 для тестов
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:domain1-db;MODE=PostgreSQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS LIQUIBASE\;CREATE SCHEMA IF NOT EXISTS DICT\;SET SCHEMA DICT;
    username: sa
    password:
  liquibase:
    user: sa
    password:
    contexts: schema