spring:
  profiles:
    default: local #??????? Spring ?? ?????????
  datasource: #????????? ?????????? ? ???? ?? ?????????
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres #????? ????????????? ????? ?????????? ?????????
    username: postgres
    password: SRr729038
  jpa:
    show-sql: false #?? ????????? ???????? ????? SQL
    hibernate.ddl-auto: validate #Hibernate ????? ?????? ????????? ????? 
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  liquibase:
    enabled: true #??????? ?? ?????????
    contexts: schema, data #????????? ?? ?????????
    change-log: classpath:db.changelog.xml #???? ? ??????? ????????? Liquibase
    liquibaseSchema: public #????????? ????? ???? ??? liquibase
    default-schema: dict #????? ???? ??? ??????????
    user: postgres
    password: SRr729038
---
spring:
  config.activate.on-profile: test #?????????? ???????? ???????? ??? ????????? ??????? 
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect #?????????? H2 ??? ??????
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres #????? ????????????? ????? ?????????? ?????????
    username: postgres
    password: SRr729038
  liquibase:
    user: postgres
    password: SRr729038
    contexts: schema