spring:
  profiles:
    default: local
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://rc1b-46tfuv14tfrye5c8.mdb.yandexcloud.net:6432/db1?&targetServerType=master&ssl=true&sslmode=verify-full
    username:
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: create

---
spring:
  config.activate.on-profile: test #?????????? ???????? ???????? ??? ????????? ???????
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect #?????????? H2 ??? ??????
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://rc1b-46tfuv14tfrye5c8.mdb.yandexcloud.net:6432/db1?&targetServerType=master&ssl=true&sslmode=verify-full
    username: user1
    password: SRr729038